name: linux commands
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  DEV-Deployment:
    runs-on: self-hosted
    environment: Dev
    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: sh ./script.sh
  Prod-Deployment:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo what is installed in it?
          python -V
          ls -a
          whoami
          env
          hostname
          pwd
          free
          df -h
