name: linux commands
'on':
  #push:
  #  branches:
  #    - main
  #pull_request:
  #  branches:
  #    - main

  workflow_dispatch:
    inputs:
      changenumber:
          description: 'pass change request number'
          default: ''
          required: true
          type: string

jobs:
  DEV-Deployment:
    runs-on: self-hosted
    environment: Dev
    steps:
    - uses: actions/checkout@v3
    - name: unzip files
      run: |
          echo "unzip files"
          unzip -o *.zip
    - name: Run a one-line script
      run: sh ./script.sh ${{ secrets.PASSWORD1 }} ${{ secrets.PASSWORD2 }}
    - name: parameter validation
      run: echo "change request number is ${{ inputs.changenumber }}" 
      
  Prod-Deployment:
    runs-on: ubuntu-latest
    needs: DEV-Deployment
    environment: Prod
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo what is installed in it?
          python -V
          ls -a
          whoami
          env
          hostname
          pwd
          free
          df -h
